server:
  port: ${SERVER_PORT:9000}
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false

spring:
  jmx:
    enabled: true
    default_domain: Kafdrop
  jackson:
    deserialization:
      fail_on_unknown_properties: false
      read_unknown_enum_values_as_null: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure.include: "*"
  server:
    port: 9000

kafdrop.monitor:
  clientId: Kafdrop
topic:
  createEnabled:false
kafka:
  brokerConnect: kafka-850815958-4-864307700.stg-southcentralus-az.kafka-health-wellness-stg.ms-df-messaging.stg-az-southcentralus-7.prod.us.walmart.net:5731
  isSecured: true
  saslMechanism: "PLAIN"
  securityProtocol: "SASL_PLAINTEXT"
  truststoreFile: "${KAFKA_TRUSTSTORE_FILE:kafka.truststore.jks}"
  propertiesFile : "${KAFKA_PROPERTIES_FILE:kafka.properties}"
  keystoreFile: "${KAFKA_KEYSTORE_FILE:kafka.keystore.jks}"